export const SELECT_CHARACTER = 'SELECT_CHARACTER';
export const UNSELECT_CHARACTER = 'UNSELECT_CHARACTER';
export const LOAD_CHARACTERS = 'LOAD_CHARACTERS';
export const ATTACK_0 = 'ATTACK_0';
export const ATTACK_1 = 'ATTACK_1';