- name: install pip to install docker-compose dependencies
  apt:
    name: python3-pip
    state: present

- name: install docker-compose dependencies
  pip:
    name: "docker"
    state: present

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    force: True
    owner: "root"
    group: "root"
    mode: "0755"

- name: install docker-compose with pip
  pip:
    name: "docker-compose"
    state: present

- name: install docker with pip
  pip:
    name: "docker"
    state: present
