// Section
export const SET_HOME = "SET_HOME";
export const SET_CREATE_CHARACTER = "SET_CREATE_CHARACTER";
export const SET_FIGHT = "SET_FIGHT";
export const SET_SETTINGS = "SET_SETTINGS";
export const SET_TEST = "SET_TEST";

// Character
export const SELECT_CHARACTER = "SELECT_CHARACTER";
export const UNSELECT_CHARACTER = "UNSELECT_CHARACTER";
export const CLEAR_SELECTION = "CLEAR_SELECTION";
export const ADD_CHARACTER = "ADD_CHARACTER";
export const GET_CHARACTERS = "GET_CHARACTERS";
export const LOADING_CHARACTERS = "LOADING_CHARACTERS";

// Fight
export const LOAD_CHARACTERS = "LOAD_CHARACTERS";
export const CLEAR_FIGHT = "CLEAR_FIGHT";
export const ATTACK_0 = "ATTACK_0";
export const ATTACK_1 = "ATTACK_1";
export const SKILL1_0 = "SKILL1_0";
export const SKILL1_1 = "SKILL1_1";
export const ULTIMATE_0 = "ULTIMATE_0";
export const ULTIMATE_1 = "ULTIMATE_1";
export const SET_WINNER = "SET_WINNER";

// Multiplayer
export const CREATE_SOCKET = "CREATE_SOCKET";
export const RECIEVE_MESSAGE = "RECIEVE_MESSAGE";
export const SELECT_MULTIPLAYER_CHARACTER = "SELECT_MULTIPLAYER_CHARACTER";
export const UNSELECT_MULTIPLAYER_CHARACTER = "UNSELECT_MULTIPLAYER_CHARACTER";
export const ENEMY_SELECT_CHARACTER = "ENEMY_SELECT_CHARACTER";
export const GET_USERS = "GET_USERS";

// Error
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";